workspaces:
  - name: api
    path: ~/workspace/polyrepo-dev
    repositories:
      - url: git@github.com:polyrepopro/api.git
        branch: main
        path: pkg/api
        auth:
          key: ~/.ssh/id_rsa
      - url: git@github.com:polyrepopro/cli.git
        branch: main
        path: pkg/cli
        auth:
          key: ~/.ssh/id_rsa
